### ISSUE TITLE
NJ 2023 joint 2x9K wages

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#109]
NJ 2023 joint 2x9K wages

http://taxsim.nber.org/out2psl/nj

Emulator - -2395, Tax Act -2598.

**Comment by PavelMakarchuk** [comment]
@feenberg this difference is due to PE-US calculating a tax amount of $203 which I am checking agains the [tax rate schedule](https://www.nj.gov/treasury/taxation/pdf/current/1040i.pdf#page=65):
![image](https://github.com/user-attachments/assets/8acea265-2c34-4db3-beaf-20651ae530d2)

Not sure why TaxAct does not include this amount - the refundable credit amounts are equal in TaxAct and PE
